### ISSUE TITLE
上传DYSM错误

### ISSUE THREAD

**Issue by panjiulong** [srv7/upload_dsym_to_bugly#4]
这是我的脚本
```
lane :upToAppStore do|options|

branch = options[:branch]

#cocoapods

updateProjectBuildNumber #更改项目build号

gym(
#输出的ipa名称
output_name:"#{output_name}",
#指定项目的scheme
scheme:"#{scheme}",
# 是否清空以前的编译信息 true：是
clean:true,
# 指定打包方式，Release 或者 Debug
configuration:"Release",
# 指定打包所使用的输出方式，目前支持app-store, package, ad-hoc, enterprise, development
export_method:"app-store",
# 指定输出文件夹
output_directory:"#{output_directory}appstore",
)
output_dysm_name = "#{output_name}.app.dSYM.zip"

puts "#{output_dysm_name}--------##{output_directory}appstore/#{output_dysm_name}--#{get_version_number}"

upload_dsym_to_bugly(
      file_path: "#{output_directory}/#{output_dysm_name}",
      file_name: "#{output_dysm_name}",
      app_key: "#{buglyAppkey}",
      app_id: "#{buglyAppId}",
      api_version: 1,
      symbol_type: 2, # iOS => 2, Android => 1
      bundle_id: 'com.xiaonianyu',
      product_version: get_version_number
    )
puts “*************| 上传DYSM到Bugly成功 |*************”
```
下面是打印的日志

[13:49:34]: *************| 上传DYSM到Bugly |*************
[13:49:34]: [32m--------------------------------[0m
[13:49:34]: [32m--- Step: get_version_number ---[0m
[13:49:34]: [32m--------------------------------[0m
[13:49:34]: xny-app-ios_202012.21.1.app.dSYM.zip--------#~/Desktop/fastlaneBuild/xny/appstore/xny-app-ios_202012.21.1.app.dSYM.zip--2.2.3
[13:49:34]: [32m--------------------------------[0m
[13:49:34]: [32m--- Step: get_version_number ---[0m
[13:49:34]: [32m--------------------------------[0m
[13:49:34]: [32m----------------------------------[0m
[13:49:34]: [32m--- Step: upload_dsym_to_bugly ---[0m
[13:49:34]: [32m----------------------------------[0m
[13:49:34]: file path: ~/Desktop/fastlaneBuild/xny/appstore/xny-app-ios_202012.21.1.app.dSYM.zip
[13:49:34]: api_version:  --form "api_version=1" 
[13:49:34]: channel:  --form "channel=fastlane" 
[13:49:34]: [36m$ curl -k "https://api.bugly.qq.com/openapi/file/upload/symbol?app_key=6ebd02af-8eb3-433e-8e9f-8dcb1c08e22e&app_id=15b0c82706" --form "api_version=1"  --form "app_id=15b0c82706" --form "app_key=6ebd02af-8eb3-433e-8e9f-8dcb1c08e22e" --form "symbolType=2" --form "bundleId=com.xiaonianyu" --form "productVersion=2.2.3" --form "channel=fastlane"  --form "fileName=xny-app-ios_202012.21.1.app.dSYM.zip" --form "file=@~/Desktop/fastlaneBuild/xny/appstore/xny-app-ios_202012.21.1.app.dSYM.zip" -o upload_dsym_to_bugly_result.json[0m
[13:49:34]: ▸ [35mcurl: (26) Failed to open/read local data from file/application[0m
[13:49:34]: dSYM upload failed
+-----------------------------+-----------------------------------------------------------------------------------------------------------------------+
|                                                                    [33mLane Context[0m                                                                     |
+-----------------------------+-----------------------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM            | ios                                                                                                                   |
| BUILD_NUMBER                | 20210118.01                                                                                                           |
| PLATFORM_NAME               | ios                                                                                                                   |
| LANE_NAME                   | ios upToAppStore                                                                                                      |
| IPA_OUTPUT_PATH             | /Users/zhangmanyang/Desktop/fastlaneBuild/xny/appstore/xny-app-ios_202012.21.1.ipa                                    |
| XCODEBUILD_ARCHIVE          | /Users/zhangmanyang/Library/Developer/Xcode/Archives/2021-01-18/xny-app-ios_202012.21.1 2021-01-18 13.45.17.xcarchive |
| DSYM_OUTPUT_PATH            | /Users/zhangmanyang/Desktop/fastlaneBuild/xny/appstore/xny-app-ios_202012.21.1.app.dSYM.zip                           |
| VERSION_NUMBER              | 2.2.3                                                                                                                 |
| UPLOAD_DSYM_TO_BUGLY_RESULT | false                                                                                                                 |
+-----------------------------+-----------------------------------------------------------------------------------------------------------------------+
[13:49:34]: [31mExit status of command 'curl -k "https://api.bugly.qq.com/openapi/file/upload/symbol?app_key=6ebd02af-8eb3-433e-8e9f-8dcb1c08e22e&app_id=15b0c82706" --form "api_version=1"  --form "app_id=15b0c82706" --form "app_key=6ebd02af-8eb3-433e-8e9f-8dcb1c08e22e" --form "symbolType=2" --form "bundleId=com.xiaonianyu" --form "productVersion=2.2.3" --form "channel=fastlane"  --form "fileName=xny-app-ios_202012.21.1.app.dSYM.zip" --form "file=@~/Desktop/fastlaneBuild/xny/appstore/xny-app-ios_202012.21.1.app.dSYM.zip" -o upload_dsym_to_bugly_result.json' was 26 instead of 0.
curl: (26) Failed to open/read local data from file/application
[0m

+------+----------------------------+-------------+
|                [32mfastlane summary[0m                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | get_build_number           | 0           |
| 4    | get_build_number           | 0           |
| 5    | increment_build_number     | 0           |
| 6    | gym                        | 262         |
| 7    | get_version_number         | 0           |
| 8    | get_version_number         | 0           |
| 💥   | [31mupload_dsym_to_bugly[0m       | 0           |
+------+----------------------------+-------------+

[13:49:34]: [31mfastlane finished with errors[0m

Looking for related GitHub issues on fastlane/fastlane...

/Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [31m[!] Exit status of command 'curl -k "https://api.bugly.qq.com/openapi/file/upload/symbol?app_key=6ebd02af-8eb3-433e-8e9f-8dcb1c08e22e&app_id=15b0c82706" --form "api_version=1"  --form "app_id=15b0c82706" --form "app_key=6ebd02af-8eb3-433e-8e9f-8dcb1c08e22e" --form "symbolType=2" --form "bundleId=com.xiaonianyu" --form "productVersion=2.2.3" --form "channel=fastlane"  --form "fileName=xny-app-ios_202012.21.1.app.dSYM.zip" --form "file=@~/Desktop/fastlaneBuild/xny/appstore/xny-app-ios_202012.21.1.app.dSYM.zip" -o upload_dsym_to_bugly_result.json' was 26 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
curl: (26) Failed to open/read local data from file/application
[0m
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-2.171.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /Users/zhangmanyang/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/forwardable.rb:230:in `sh'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-plugin-upload_dsym_to_bugly-1.1.2/lib/fastlane/plugin/upload_dsym_to_bugly/actions/upload_dsym_to_bugly_action.rb:39:in `run'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-2.171.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-2.171.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:124:in `block (2 levels) in parsing_binding'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-2.171.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-2.171.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-2.171.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-2.171.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/zhangmanyang/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/zhangmanyang/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/zhangmanyang/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/zhangmanyang/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-2.171.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-2.171.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-2.171.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/gems/fastlane-2.171.0/bin/fastlane:23:in `<top (required)>'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/bin/fastlane:23:in `load'
	from /Users/zhangmanyang/.rvm/gems/ruby-2.6.2/bin/fastlane:23:in `<main>'
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by srv7** [comment]
> curl -k "https://api.bugly.qq.com/openapi/file/upload/symbol?app_key=6ebd02af-8eb3-433e-8e9f-8dcb1c08e22e&app_id=15b0c82706" --form "api_version=1" --form "app_id=15b0c82706" --form "app_key=6ebd02af-8eb3-433e-8e9f-8dcb1c08e22e" --form "symbolType=2" --form "bundleId=com.xiaonianyu" --form "productVersion=2.2.3" --form "channel=fastlane" --form "fileName=xny-app-ios_202012.21.1.app.dSYM.zip" --form "file=@~/Desktop/fastlaneBuild/xny/appstore/xny-app-ios_202012.21.1.app.dSYM.zip" -o upload_dsym_to_bugly_result.json

--form "file=@~/Desktop/fastlaneBuild/xny/appstore/xny-app-ios_202012.21.1.app.dSYM.zip" 这个字段出错
请检查 file_path: "#{output_directory}/#{output_dysm_name}",
      file_name: "#{output_dysm_name}",

**Comment by panjiulong** [comment]
[20:00:54]: *************| 上传DYSM到Bugly |*************
[20:00:54]: [32m--------------------------------[0m
[20:00:54]: [32m--- Step: get_version_number ---[0m
[20:00:54]: [32m--------------------------------[0m
[20:00:54]: [32m----------------------------------[0m
[20:00:54]: [32m--- Step: upload_dsym_to_bugly ---[0m
[20:00:54]: [32m----------------------------------[0m
[20:00:54]: file path: /Users/zhangmanyang/Desktop/fastlaneBuild/xny/appstore/xny-app-ios_20210329.1955.app.dSYM.zip
[20:00:54]: api_version:  --form "api_version=1" 
[20:00:54]: channel:  --form "channel=fastlane" 
[20:00:54]: [36m$ curl -k "https://api.bugly.qq.com/openapi/file/upload/symbol?app_key=6ebd02af-8eb3-433e-8e9f-8dcb1c08e22e&app_id=15b0c89706" --form "api_version=1"  --form "app_id=15b0c89706" --form "app_key=6ebd02af-8eb3-433e-8e9f-8dcb1c08e22e" --form "symbolType=2" --form "bundleId=com.xiaonianyu" --form "productVersion=2.2.10" --form "channel=fastlane"  --form "fileName=xny-app-ios_20210329.1955.app.dSYM.zip" --form "file=@/Users/zhangmanyang/Desktop/fastlaneBuild/xny/appstore/xny-app-ios_20210329.1955.app.dSYM.zip" -o upload_dsym_to_bugly_result.json[0m
[20:00:54]: ▸ [35m% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current[0m
[20:00:54]: ▸ [35mDload  Upload   Total   Spent    Left  Speed[0m
[20:01:16]: ▸ [35m100 42.5M  100    55  100 42.5M      2  2001k  0:00:27  0:00:21  0:00:06    14[0m
[20:01:16]: dSYM upload success
[20:01:16]: *************| 上传DYSM到Bugly成功 |*************


显示上传成功了，但是bugly上却没有显示符号表

**Comment by srv7** [comment]
我也遇到过这种情况，请检查一下你的 dsym 是不是包含了其他三方库的 dsym，如果 dsym 文件过大的话，bugly 会吞掉这个 符号表
